fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "api_request",
            "api_cancel",
            "backend_status",
            "open_repository",
            "open_ocs_docs",
            "session_read",
            "session_remember_login",
            "session_remember_task",
            "session_clear",
            "close_prompt_shown",
            "close_choice",
            "preferences_read",
            "preferences_write",
        ]),
    ))
    .unwrap();
}
